FROM golang:1.22.2
COPY . /go/src/github.com/quilla-hq/quilla
WORKDIR /go/src/github.com/quilla-hq/quilla
RUN make build

FROM debian:latest
RUN apt-get update && apt-get install -y \
  ca-certificates \
  && rm -rf /var/lib/apt/lists/*

COPY --from=0 /go/src/github.com/quilla-hq/quilla/cmd/quilla/quilla /bin/quilla
ENTRYPOINT ["/bin/quilla"]

EXPOSE 9300
