FROM node:lts-alpine as ui
WORKDIR /app
COPY ui /app
RUN yarn
RUN yarn run lint --no-fix
RUN yarn run build

FROM arm32v7/debian:buster
ADD ca-certificates.crt /etc/ssl/certs/
COPY cmd/quilla/release/quilla-linux-arm /bin/quilla
COPY --from=ui /app/dist /www
VOLUME /data
ENV XDG_DATA_HOME /data

EXPOSE 9300
ENTRYPOINT ["/bin/quilla"]