{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name | default (include "quilla.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "quilla.name" . }}
    chart: {{ template "quilla.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
{{- if (and .Values.azure.enabled .Values.azure.clientId) }}
  AZURE_CLIENT_ID: {{ .Values.azure.clientId | b64enc }}
{{- end }}
{{- if (and .Values.acr.enabled .Values.acr.clientSecret) }}
  AZURE_CLIENT_SECRET: {{ .Values.acr.clientSecret | b64enc }}
{{- end }}
{{- if (and .Values.azure.enabled .Values.azure.tenantId)}}
  AZURE_TENANT_ID: {{ .Values.azure.tenantId | b64enc }}
{{- end }}
{{- if (and .Values.azure.enabled .Values.azure.redirectUri)}}
  AZURE_REDIRECT_URI: {{ .Values.azure.redirectUri | b64enc }}
{{- end }}
{{- if (and .Values.ecr.enabled .Values.ecr.secretAccessKey) }}
  AWS_SECRET_ACCESS_KEY:  {{ .Values.ecr.secretAccessKey | b64enc }}
{{- end }}
{{- if .Values.apiRBAC.enabled }}
  RBAC_POLICY: {{ .Values.apiRBAC.policy | b64enc }}
{{- end }}
{{- if .Values.slack.enabled }}
  SLACK_TOKEN: {{ .Values.slack.token | b64enc }}
{{- end }}
{{- if .Values.googleApplicationCredentials }}
  google-application-credentials.json: {{ .Values.googleApplicationCredentials }}
{{- end }}
{{- if .Values.hipchat.enabled }}
  HIPCHAT_TOKEN: {{ .Values.hipchat.token | b64enc}}
  HIPCHAT_APPROVALS_PASSWORT: {{ .Values.hipchat.password | b64enc }}
{{- end }}
{{- if .Values.teams.enabled }}
  TEAMS_WEBHOOK_URL: {{ .Values.teams.webhookUrl | b64enc }}
{{- end }}
{{- if .Values.discord.enabled }}
  DISCORD_WEBHOOK_URL: {{ .Values.discord.webhookUrl | b64enc }}
{{- end }}
{{- if and .Values.mail.enabled .Values.mail.smtp.pass }}
  MAIL_SMTP_PASS: {{ .Values.mail.smtp.pass | b64enc }}
{{- end }}
{{- if .Values.basicauth.enabled }}
  BASIC_AUTH_PASSWORD: {{ .Values.basicauth.password | b64enc }}
{{- end }}
{{- end }}
